// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.6
// source: sumofpb/sumof.proto

package sumofpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sumof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Sumof) Reset() {
	*x = Sumof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sumofpb_sumof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sumof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sumof) ProtoMessage() {}

func (x *Sumof) ProtoReflect() protoreflect.Message {
	mi := &file_sumofpb_sumof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sumof.ProtoReflect.Descriptor instead.
func (*Sumof) Descriptor() ([]byte, []int) {
	return file_sumofpb_sumof_proto_rawDescGZIP(), []int{0}
}

func (x *Sumof) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Sumof) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type SumofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val1 int32 `protobuf:"varint,1,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2 int32 `protobuf:"varint,2,opt,name=val2,proto3" json:"val2,omitempty"`
}

func (x *SumofRequest) Reset() {
	*x = SumofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sumofpb_sumof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumofRequest) ProtoMessage() {}

func (x *SumofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sumofpb_sumof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumofRequest.ProtoReflect.Descriptor instead.
func (*SumofRequest) Descriptor() ([]byte, []int) {
	return file_sumofpb_sumof_proto_rawDescGZIP(), []int{1}
}

func (x *SumofRequest) GetVal1() int32 {
	if x != nil {
		return x.Val1
	}
	return 0
}

func (x *SumofRequest) GetVal2() int32 {
	if x != nil {
		return x.Val2
	}
	return 0
}

type SumofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SumofResponse) Reset() {
	*x = SumofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sumofpb_sumof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumofResponse) ProtoMessage() {}

func (x *SumofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sumofpb_sumof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumofResponse.ProtoReflect.Descriptor instead.
func (*SumofResponse) Descriptor() ([]byte, []int) {
	return file_sumofpb_sumof_proto_rawDescGZIP(), []int{2}
}

func (x *SumofResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_sumofpb_sumof_proto protoreflect.FileDescriptor

var file_sumofpb_sumof_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x75, 0x6d, 0x6f, 0x66, 0x70, 0x62, 0x2f, 0x73, 0x75, 0x6d, 0x6f, 0x66, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x75, 0x6d, 0x6f, 0x66, 0x22, 0x23, 0x0a, 0x05,
	0x53, 0x75, 0x6d, 0x6f, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x62, 0x22, 0x36, 0x0a, 0x0c, 0x53, 0x75, 0x6d, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x76, 0x61, 0x6c, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x75, 0x6d,
	0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x44, 0x0a, 0x0c, 0x53, 0x75, 0x6d, 0x6f, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x75, 0x6d, 0x6f, 0x66, 0x12, 0x13, 0x2e, 0x73, 0x75,
	0x6d, 0x6f, 0x66, 0x2e, 0x53, 0x75, 0x6d, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x73, 0x75, 0x6d, 0x6f, 0x66, 0x2e, 0x53, 0x75, 0x6d, 0x6f, 0x66, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x75,
	0x6d, 0x6f, 0x66, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sumofpb_sumof_proto_rawDescOnce sync.Once
	file_sumofpb_sumof_proto_rawDescData = file_sumofpb_sumof_proto_rawDesc
)

func file_sumofpb_sumof_proto_rawDescGZIP() []byte {
	file_sumofpb_sumof_proto_rawDescOnce.Do(func() {
		file_sumofpb_sumof_proto_rawDescData = protoimpl.X.CompressGZIP(file_sumofpb_sumof_proto_rawDescData)
	})
	return file_sumofpb_sumof_proto_rawDescData
}

var file_sumofpb_sumof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sumofpb_sumof_proto_goTypes = []interface{}{
	(*Sumof)(nil),         // 0: sumof.Sumof
	(*SumofRequest)(nil),  // 1: sumof.SumofRequest
	(*SumofResponse)(nil), // 2: sumof.SumofResponse
}
var file_sumofpb_sumof_proto_depIdxs = []int32{
	1, // 0: sumof.SumofService.Sumof:input_type -> sumof.SumofRequest
	2, // 1: sumof.SumofService.Sumof:output_type -> sumof.SumofResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sumofpb_sumof_proto_init() }
func file_sumofpb_sumof_proto_init() {
	if File_sumofpb_sumof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sumofpb_sumof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sumof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sumofpb_sumof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sumofpb_sumof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sumofpb_sumof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sumofpb_sumof_proto_goTypes,
		DependencyIndexes: file_sumofpb_sumof_proto_depIdxs,
		MessageInfos:      file_sumofpb_sumof_proto_msgTypes,
	}.Build()
	File_sumofpb_sumof_proto = out.File
	file_sumofpb_sumof_proto_rawDesc = nil
	file_sumofpb_sumof_proto_goTypes = nil
	file_sumofpb_sumof_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SumofServiceClient is the client API for SumofService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumofServiceClient interface {
	//Unary
	Sumof(ctx context.Context, in *SumofRequest, opts ...grpc.CallOption) (*SumofResponse, error)
}

type sumofServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSumofServiceClient(cc grpc.ClientConnInterface) SumofServiceClient {
	return &sumofServiceClient{cc}
}

func (c *sumofServiceClient) Sumof(ctx context.Context, in *SumofRequest, opts ...grpc.CallOption) (*SumofResponse, error) {
	out := new(SumofResponse)
	err := c.cc.Invoke(ctx, "/sumof.SumofService/Sumof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumofServiceServer is the server API for SumofService service.
type SumofServiceServer interface {
	//Unary
	Sumof(context.Context, *SumofRequest) (*SumofResponse, error)
}

// UnimplementedSumofServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSumofServiceServer struct {
}

func (*UnimplementedSumofServiceServer) Sumof(context.Context, *SumofRequest) (*SumofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sumof not implemented")
}

func RegisterSumofServiceServer(s *grpc.Server, srv SumofServiceServer) {
	s.RegisterService(&_SumofService_serviceDesc, srv)
}

func _SumofService_Sumof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumofServiceServer).Sumof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sumof.SumofService/Sumof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumofServiceServer).Sumof(ctx, req.(*SumofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SumofService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sumof.SumofService",
	HandlerType: (*SumofServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sumof",
			Handler:    _SumofService_Sumof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sumofpb/sumof.proto",
}
