// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.6
// source: avercalcpb/avercalc.proto

package avercalcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvercalcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *AvercalcRequest) Reset() {
	*x = AvercalcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avercalcpb_avercalc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvercalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvercalcRequest) ProtoMessage() {}

func (x *AvercalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avercalcpb_avercalc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvercalcRequest.ProtoReflect.Descriptor instead.
func (*AvercalcRequest) Descriptor() ([]byte, []int) {
	return file_avercalcpb_avercalc_proto_rawDescGZIP(), []int{0}
}

func (x *AvercalcRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type AvercalcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AvercalcResponse) Reset() {
	*x = AvercalcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avercalcpb_avercalc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvercalcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvercalcResponse) ProtoMessage() {}

func (x *AvercalcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avercalcpb_avercalc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvercalcResponse.ProtoReflect.Descriptor instead.
func (*AvercalcResponse) Descriptor() ([]byte, []int) {
	return file_avercalcpb_avercalc_proto_rawDescGZIP(), []int{1}
}

func (x *AvercalcResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_avercalcpb_avercalc_proto protoreflect.FileDescriptor

var file_avercalcpb_avercalc_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x70, 0x62, 0x2f, 0x61, 0x76, 0x65,
	0x72, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x76, 0x65,
	0x72, 0x63, 0x61, 0x6c, 0x63, 0x22, 0x29, 0x0a, 0x0f, 0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x2a, 0x0a, 0x10, 0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x58, 0x0a, 0x0f,
	0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x45, 0x0a, 0x08, 0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x12, 0x19, 0x2e, 0x61, 0x76,
	0x65, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x61, 0x76, 0x65, 0x72, 0x63, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x61, 0x76, 0x65, 0x72,
	0x63, 0x61, 0x6c, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_avercalcpb_avercalc_proto_rawDescOnce sync.Once
	file_avercalcpb_avercalc_proto_rawDescData = file_avercalcpb_avercalc_proto_rawDesc
)

func file_avercalcpb_avercalc_proto_rawDescGZIP() []byte {
	file_avercalcpb_avercalc_proto_rawDescOnce.Do(func() {
		file_avercalcpb_avercalc_proto_rawDescData = protoimpl.X.CompressGZIP(file_avercalcpb_avercalc_proto_rawDescData)
	})
	return file_avercalcpb_avercalc_proto_rawDescData
}

var file_avercalcpb_avercalc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_avercalcpb_avercalc_proto_goTypes = []interface{}{
	(*AvercalcRequest)(nil),  // 0: avercalc.avercalcRequest
	(*AvercalcResponse)(nil), // 1: avercalc.avercalcResponse
}
var file_avercalcpb_avercalc_proto_depIdxs = []int32{
	0, // 0: avercalc.avercalcService.avercalc:input_type -> avercalc.avercalcRequest
	1, // 1: avercalc.avercalcService.avercalc:output_type -> avercalc.avercalcResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avercalcpb_avercalc_proto_init() }
func file_avercalcpb_avercalc_proto_init() {
	if File_avercalcpb_avercalc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_avercalcpb_avercalc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvercalcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avercalcpb_avercalc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvercalcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_avercalcpb_avercalc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avercalcpb_avercalc_proto_goTypes,
		DependencyIndexes: file_avercalcpb_avercalc_proto_depIdxs,
		MessageInfos:      file_avercalcpb_avercalc_proto_msgTypes,
	}.Build()
	File_avercalcpb_avercalc_proto = out.File
	file_avercalcpb_avercalc_proto_rawDesc = nil
	file_avercalcpb_avercalc_proto_goTypes = nil
	file_avercalcpb_avercalc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AvercalcServiceClient is the client API for AvercalcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AvercalcServiceClient interface {
	//client streaming
	Avercalc(ctx context.Context, opts ...grpc.CallOption) (AvercalcService_AvercalcClient, error)
}

type avercalcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvercalcServiceClient(cc grpc.ClientConnInterface) AvercalcServiceClient {
	return &avercalcServiceClient{cc}
}

func (c *avercalcServiceClient) Avercalc(ctx context.Context, opts ...grpc.CallOption) (AvercalcService_AvercalcClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AvercalcService_serviceDesc.Streams[0], "/avercalc.avercalcService/avercalc", opts...)
	if err != nil {
		return nil, err
	}
	x := &avercalcServiceAvercalcClient{stream}
	return x, nil
}

type AvercalcService_AvercalcClient interface {
	Send(*AvercalcRequest) error
	CloseAndRecv() (*AvercalcResponse, error)
	grpc.ClientStream
}

type avercalcServiceAvercalcClient struct {
	grpc.ClientStream
}

func (x *avercalcServiceAvercalcClient) Send(m *AvercalcRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *avercalcServiceAvercalcClient) CloseAndRecv() (*AvercalcResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AvercalcResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AvercalcServiceServer is the server API for AvercalcService service.
type AvercalcServiceServer interface {
	//client streaming
	Avercalc(AvercalcService_AvercalcServer) error
}

// UnimplementedAvercalcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAvercalcServiceServer struct {
}

func (*UnimplementedAvercalcServiceServer) Avercalc(AvercalcService_AvercalcServer) error {
	return status.Errorf(codes.Unimplemented, "method Avercalc not implemented")
}

func RegisterAvercalcServiceServer(s *grpc.Server, srv AvercalcServiceServer) {
	s.RegisterService(&_AvercalcService_serviceDesc, srv)
}

func _AvercalcService_Avercalc_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AvercalcServiceServer).Avercalc(&avercalcServiceAvercalcServer{stream})
}

type AvercalcService_AvercalcServer interface {
	SendAndClose(*AvercalcResponse) error
	Recv() (*AvercalcRequest, error)
	grpc.ServerStream
}

type avercalcServiceAvercalcServer struct {
	grpc.ServerStream
}

func (x *avercalcServiceAvercalcServer) SendAndClose(m *AvercalcResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *avercalcServiceAvercalcServer) Recv() (*AvercalcRequest, error) {
	m := new(AvercalcRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AvercalcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "avercalc.avercalcService",
	HandlerType: (*AvercalcServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "avercalc",
			Handler:       _AvercalcService_Avercalc_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "avercalcpb/avercalc.proto",
}
