// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.6
// source: divsearchpb/divsearch.proto

package divsearchpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DivsearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *DivsearchRequest) Reset() {
	*x = DivsearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_divsearchpb_divsearch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivsearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivsearchRequest) ProtoMessage() {}

func (x *DivsearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_divsearchpb_divsearch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivsearchRequest.ProtoReflect.Descriptor instead.
func (*DivsearchRequest) Descriptor() ([]byte, []int) {
	return file_divsearchpb_divsearch_proto_rawDescGZIP(), []int{0}
}

func (x *DivsearchRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type DivsearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DivsearchResponse) Reset() {
	*x = DivsearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_divsearchpb_divsearch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivsearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivsearchResponse) ProtoMessage() {}

func (x *DivsearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_divsearchpb_divsearch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivsearchResponse.ProtoReflect.Descriptor instead.
func (*DivsearchResponse) Descriptor() ([]byte, []int) {
	return file_divsearchpb_divsearch_proto_rawDescGZIP(), []int{1}
}

func (x *DivsearchResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_divsearchpb_divsearch_proto protoreflect.FileDescriptor

var file_divsearchpb_divsearch_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x70, 0x62, 0x2f, 0x64, 0x69,
	0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64,
	0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x2a, 0x0a, 0x10, 0x64, 0x69, 0x76, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x11, 0x64, 0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x5e, 0x0a, 0x10, 0x64, 0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x44, 0x69, 0x76, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x1b, 0x2e, 0x64, 0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x64,
	0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x64, 0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x64, 0x69, 0x76, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x64, 0x69, 0x76, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_divsearchpb_divsearch_proto_rawDescOnce sync.Once
	file_divsearchpb_divsearch_proto_rawDescData = file_divsearchpb_divsearch_proto_rawDesc
)

func file_divsearchpb_divsearch_proto_rawDescGZIP() []byte {
	file_divsearchpb_divsearch_proto_rawDescOnce.Do(func() {
		file_divsearchpb_divsearch_proto_rawDescData = protoimpl.X.CompressGZIP(file_divsearchpb_divsearch_proto_rawDescData)
	})
	return file_divsearchpb_divsearch_proto_rawDescData
}

var file_divsearchpb_divsearch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_divsearchpb_divsearch_proto_goTypes = []interface{}{
	(*DivsearchRequest)(nil),  // 0: divsearch.divsearchRequest
	(*DivsearchResponse)(nil), // 1: divsearch.divsearchResponse
}
var file_divsearchpb_divsearch_proto_depIdxs = []int32{
	0, // 0: divsearch.divsearchService.DivSearch:input_type -> divsearch.divsearchRequest
	1, // 1: divsearch.divsearchService.DivSearch:output_type -> divsearch.divsearchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_divsearchpb_divsearch_proto_init() }
func file_divsearchpb_divsearch_proto_init() {
	if File_divsearchpb_divsearch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_divsearchpb_divsearch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivsearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_divsearchpb_divsearch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivsearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_divsearchpb_divsearch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_divsearchpb_divsearch_proto_goTypes,
		DependencyIndexes: file_divsearchpb_divsearch_proto_depIdxs,
		MessageInfos:      file_divsearchpb_divsearch_proto_msgTypes,
	}.Build()
	File_divsearchpb_divsearch_proto = out.File
	file_divsearchpb_divsearch_proto_rawDesc = nil
	file_divsearchpb_divsearch_proto_goTypes = nil
	file_divsearchpb_divsearch_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DivsearchServiceClient is the client API for DivsearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DivsearchServiceClient interface {
	//Unary
	DivSearch(ctx context.Context, in *DivsearchRequest, opts ...grpc.CallOption) (DivsearchService_DivSearchClient, error)
}

type divsearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDivsearchServiceClient(cc grpc.ClientConnInterface) DivsearchServiceClient {
	return &divsearchServiceClient{cc}
}

func (c *divsearchServiceClient) DivSearch(ctx context.Context, in *DivsearchRequest, opts ...grpc.CallOption) (DivsearchService_DivSearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DivsearchService_serviceDesc.Streams[0], "/divsearch.divsearchService/DivSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &divsearchServiceDivSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DivsearchService_DivSearchClient interface {
	Recv() (*DivsearchResponse, error)
	grpc.ClientStream
}

type divsearchServiceDivSearchClient struct {
	grpc.ClientStream
}

func (x *divsearchServiceDivSearchClient) Recv() (*DivsearchResponse, error) {
	m := new(DivsearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DivsearchServiceServer is the server API for DivsearchService service.
type DivsearchServiceServer interface {
	//Unary
	DivSearch(*DivsearchRequest, DivsearchService_DivSearchServer) error
}

// UnimplementedDivsearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDivsearchServiceServer struct {
}

func (*UnimplementedDivsearchServiceServer) DivSearch(*DivsearchRequest, DivsearchService_DivSearchServer) error {
	return status.Errorf(codes.Unimplemented, "method DivSearch not implemented")
}

func RegisterDivsearchServiceServer(s *grpc.Server, srv DivsearchServiceServer) {
	s.RegisterService(&_DivsearchService_serviceDesc, srv)
}

func _DivsearchService_DivSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DivsearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DivsearchServiceServer).DivSearch(m, &divsearchServiceDivSearchServer{stream})
}

type DivsearchService_DivSearchServer interface {
	Send(*DivsearchResponse) error
	grpc.ServerStream
}

type divsearchServiceDivSearchServer struct {
	grpc.ServerStream
}

func (x *divsearchServiceDivSearchServer) Send(m *DivsearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _DivsearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "divsearch.divsearchService",
	HandlerType: (*DivsearchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DivSearch",
			Handler:       _DivsearchService_DivSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "divsearchpb/divsearch.proto",
}
